import type { ScenarioConfig } from "./types";

export const scenarios: ScenarioConfig[] = [
  {
    id: "charging-rest",
    title: "补能与休息",
    hypothesis: "用户可能愿意把补能和休息合并为一次停靠",
    passiveCopy: "前方 12 km 有充电站",
    probeCopy: "前方充电站停一下吧？",
    primaryAction: "停一下",
    secondaryAction: "继续走",
    confirmTitle: "前方充电站",
    confirmMeta: "预计停留 20 分钟",
    confirmPrimary: "加入行程",
    confirmSecondary: "调整",
    resultCopy: "已加入前方充电站",
    resultMeta: "预计到达时间已更新",
    undoCopy: "已撤销路线变更",
    intentMorph: {
      lowClues: ["18%", "前方 12 km"],
      midEvidence: ["电量 18%", "距离 12 km"],
      keyword: "前方充电站",
      midPrefix: "",
      midSuffix: "",
      midSupport: "适合短暂休息",
      highPrefix: "",
      highSuffix: "停一下吧？",
      midActionCopy: "停靠方案",
      actionHint: "预计 20 分钟",
    },
    corrections: [
      { id: "rest-only", label: "只休息", acknowledgement: "明白，只找休息点。", title: "前方 8 km 服务区", meta: "适合短暂休息", resultCopy: "已加入前方服务区" },
      { id: "short-charge", label: "缩短停留", acknowledgement: "好，不停太久。", title: "前方快充站", meta: "预计停留 12 分钟", resultCopy: "已加入前方快充站" },
    ],
    confidence: "mid",
    expression: 0.6,
    agency: 0.2,
    confidenceScripts: {
      low: {
        hypothesis: "可能需要补能",
        signals: [
          { label: "剩余电量", value: "31%", strength: 0.42, aligned: true },
          { label: "前方充电站", value: "24 km", strength: 0.3, aligned: true },
          { label: "连续行驶", value: "52 分钟", strength: 0.18, aligned: false },
        ],
      },
      mid: {
        hypothesis: "可能需要停车休息",
        signals: [
          { label: "连续行驶", value: "2 小时 18 分", strength: 0.82, aligned: true },
          { label: "剩余电量", value: "18%", strength: 0.9, aligned: true },
          { label: "身体状态", value: "轻微疲劳", strength: 0.62, aligned: true },
          { label: "前方充电站", value: "12 km", strength: 0.76, aligned: true },
        ],
      },
      high: {
        hypothesis: "停车补能方向已成立",
        signals: [
          { label: "连续行驶", value: "2 小时 26 分", strength: 0.94, aligned: true },
          { label: "剩余电量", value: "16%", strength: 0.96, aligned: true },
          { label: "身体状态", value: "持续疲劳", strength: 0.84, aligned: true },
          { label: "前方充电站", value: "8 km", strength: 0.9, aligned: true },
          { label: "用户反馈", value: "已接住试探", strength: 1, aligned: true },
        ],
      },
    },
  },
  {
    id: "habitual-destination",
    title: "习惯目的地",
    hypothesis: "用户今天可能仍然想去常去的健身房",
    passiveCopy: "接近平时出发时间",
    probeCopy: "今天还去健身吗？",
    primaryAction: "去",
    secondaryAction: "今天不去",
    confirmTitle: "去常去的健身房",
    confirmMeta: "预计 19:18 到达",
    confirmPrimary: "开始导航",
    confirmSecondary: "调整",
    resultCopy: "正在前往健身房",
    resultMeta: "已使用常用路线",
    undoCopy: "已取消本次导航",
    intentMorph: {
      lowClues: ["19:00", "健身"],
      midEvidence: ["19:00", "连续 4 天"],
      keyword: "健身",
      midPrefix: "接近往常的",
      midSuffix: "时间",
      highPrefix: "今天还去",
      highSuffix: "吗？",
      midActionCopy: "健身行程",
      actionHint: "沿用常用路线",
    },
    corrections: [
      { id: "other-gym", label: "换一家", acknowledgement: "好，改去公司附近那家。", title: "公司附近健身房", meta: "预计 19:25 到达", resultCopy: "正在前往公司附近健身房" },
      { id: "later", label: "晚点出发", acknowledgement: "好，八点再出发。", title: "20:00 前往健身房", meta: "到时再确认，不立即导航", resultCopy: "已安排八点出发" },
      { id: "walk", label: "改去散步", acknowledgement: "好，找一个适合散步的地方。", title: "附近滨水步道", meta: "步行环境舒适", resultCopy: "已设为附近滨水步道" },
    ],
    confidence: "mid",
    expression: 0.58,
    agency: 0.18,
    confidenceScripts: {
      low: {
        hypothesis: "可能接近出发时间",
        signals: [
          { label: "当前时间", value: "18:42", strength: 0.34, aligned: true },
          { label: "历史习惯", value: "出现 2 次", strength: 0.28, aligned: false },
          { label: "当前位置", value: "与往常不同", strength: 0.18, aligned: false },
        ],
      },
      mid: {
        hypothesis: "可能仍想去健身房",
        signals: [
          { label: "当前时间", value: "18:56", strength: 0.78, aligned: true },
          { label: "历史习惯", value: "连续 4 天", strength: 0.86, aligned: true },
          { label: "当前位置", value: "与往常相近", strength: 0.7, aligned: true },
          { label: "当前目的地", value: "尚未设置", strength: 0.64, aligned: true },
        ],
      },
      high: {
        hypothesis: "前往健身房方向已成立",
        signals: [
          { label: "当前时间", value: "19:01", strength: 0.92, aligned: true },
          { label: "历史习惯", value: "连续 5 天", strength: 0.96, aligned: true },
          { label: "当前位置", value: "与往常一致", strength: 0.9, aligned: true },
          { label: "用户反馈", value: "已接住试探", strength: 1, aligned: true },
        ],
      },
    },
  },
];
